// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
	"aws_cognito_region": "us-east-2",
	"aws_user_pools_id": "us-east-2_oLZ59kYtJ",
	"aws_user_pools_web_client_id": "5f7s5al1cljbc96bo3g8b2i60e",
    "aws_appsync_graphqlEndpoint": "https://6rkhwuq4izhxdoubmye2stukza.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
